### ISSUE TITLE
MetaplexError: AuctionHouseProgram > A seeds constraint was violated

### ISSUE THREAD

**Issue by samia-invozone** [metaplex-foundation/js#288]
I have successfully placed a bid but while running executeSale method, I'm getting an error(A seeds constraint was violated). Did someone ever face this issue? Below is the code I'm using for executing the sale.
` const purchase = await metaplex
        .auctions()
        .for(auctionHouse)
        .executeSale({
          listing: listing,
          bid: bid,
        })
        .run();`

**Comment by devusvulgaris** [comment]
I faced the same issue. @samia-invozone, have you found the solution? Looks like it happened to Candy machine as well before.

**Comment by samia-invozone** [comment]
@devusvulgaris Yes, I have resolved it. In my case, it was the bid amount issue. ExecuteSale will work if your bid amount is equivalent to the listed amount.

**Comment by coolb0y** [comment]
This still needs to fixed . Because if we want to purchase at listing price then the direct buy operation exists . What if a bidder bid at lower amount and lister thinks that the bid amount is ok and he want to sell at that price then no such method exists as of now . Unless you make lister relist at lower price and execute .buy operation instead
