### ISSUE TITLE
unable to input ATA in newTokenAccount printNewEdition

### ISSUE THREAD

**Issue by mjzuppe** [metaplex-foundation/js#375]
In seeking to diagnose and test another issue within this framework, I attempted to use `newTokenAccount` parameter in `metaplex
    .nfts()
    .printNewEdition({originalMint:, newOwner,  newTokenAccount }, operationsOptions);`
    
The language implies that this would be a parameter to feed an existing ATA, however the type is `Signer` which you can't generate for an ATA. It's used in `createTokenBuilder` to parse a destination address and to sign, yet for an ATA you'd only need the payer to sign, not the new owner. 

Permalink: https://github.com/metaplex-foundation/js/blob/99a3c43ce2bda24b6a5f62fd18b7dc07a83e78cd/packages/js/src/plugins/nftModule/operations/printNewEdition.ts#L110

I believe this parameter may be for a different intention, but I'm not sure what.

**Comment by lorisleiva** [comment]
Hi there 👋 

The `newTokenAccount` attribute is used to provide an explicit token account that is **not** the ATA.

When this attribute is provided, it will create a new "regular" Token Account at the address provided, which is why we need it to be a Signer.

If you simply want to pass in the ATA address then you must pass the `newOwner` attribute instead which defaults to the current identity.
