### ISSUE TITLE
Right after creating the NFT successfully, it throws an error like: "The account of type [MintAccount] was not found at the provided address"

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/js#430]
Right after creating the NFT successfully, it throws an error like: "The account of type [MintAccount] was not found at the provided address: ADDRESS". I'm using an Alchemy RPC. Any way we can do a retry or something? Because despite saying the mint account does not exists on this library, I can copy paste and access on Solscan right away without any problems.

**Comment by kevinfaveri** [comment]
I can solve on my end ofc, but would be cool to have a seamless experience on the library, especially since the mint address has been created, you just was not able to get the account.

**Comment by KartikSoneji** [comment]
Related:
- #406

**Comment by lorisleiva** [comment]
Hi there 👋 Thanks for raising this. Although it is using a different operation, this is actually the same issue as #344 so I'll mark this one as a duplicate.

This is a known issue due to eventual consistency that I'm hoping to resolve in the future one way or another but in the meantime, I'd recommend taking a look at my comment here: https://github.com/metaplex-foundation/js/issues/344#issuecomment-1325265657.
