### ISSUE TITLE
Overriding inserted items on CMv3 does not work

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/js#476]
Thus, this guide is invalid: https://docs.metaplex.com/programs/candy-machine/inserting-items#overriding-existing-items

I also tested with setting the index and then trying to replace 5 items. It throws CandyMachineIsFullError

**Comment by lorisleiva** [comment]
Hi there, I'm not sure why that wouldn't work since we've got a test for it.

https://github.com/metaplex-foundation/js/blob/cc4b40afb9c9f7570d0b50f8c24c9ba2df4fecb9/packages/js/test/plugins/candyMachineModule/insertCandyMachineItems.test.ts#L214

Could you check your code with this test to make sure it's okay? Otherwise, I'll need more details to be able to reproduce and fix this.

**Comment by kevinfaveri** [comment]
Yep, that's what I expected as well. Here's what I did:
- Setup the Candy machine
- Inserted all config lines to fill the entire supply on the CM
- Then, tried to reinsert all config lines again to overwrite the entire supply of the cm (100 items starting at index 0)
- When trying to reinsert, it throws CandyMachineIsFullError rather than overwriting

Monky patching the validation of "CandyMachineIsFullError" inside the "insertCandyMachineItems" (commenting it out) allows me to push this transaction, which correctly overwrites

**Comment by lorisleiva** [comment]
Thanks for raising this. I merged a fix and will be publishing a new version today.
